import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ThemeProvider } from "@/components/ThemeProvider";

const martelsansExtraLight = localFont({
  src : './fonts/MartelSans-ExtraLight.ttf',
  variable : '--font-martelsans-extralight',
  weight : "300"
})

const martelsansLight = localFont({
  src : './fonts/MartelSans-Light.ttf',
  variable: "--font-martelsans-light",
  weight : "400"
})

const martelsansRegular = localFont({
  src : './fonts/MartelSans-Regular.ttf',
  variable: "--font-martelsans-regular",
  weight : "500"
})

const martelsansSemiBold = localFont({
  src : './fonts/MartelSans-SemiBold.ttf',
  variable : '--font-martelsans-semibold',
  weight : "600"
})

const martelsansBold = localFont({
  src : './fonts/MartelSans-Bold.ttf',
  variable: "--font-martelsans-bold",
  weight : "700"
})

const martelsansExtraBold = localFont({
  src : './fonts/MartelSans-ExtraBold.ttf',
  variable: "--font-martelsans-extrabold",
  weight : "800"
})

const martelsansBlack = localFont({
  src : './fonts/MartelSans-Black.ttf',
  variable: "--font-martelsans-black",
  weight : "900"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${martelsansExtraLight.variable} ${martelsansLight.variable} ${martelsansRegular.variable} ${martelsansSemiBold.variable} ${martelsansBold.variable} ${martelsansExtraBold.variable} ${martelsansBlack.variable} antialiased`}>
      <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
